import {createCipheriv,createDecipheriv,randomBytes} from "node:crypto";
import fs from "node:fs";import path from "node:path";import {config} from "./config.js";
export interface EncryptedSecret{version:1;algorithm:"aes-256-gcm";iv:string;authTag:string;ciphertext:string}
function parseEnvKey(value:string):Buffer{const key=/^[a-f\d]{64}$/i.test(value)?Buffer.from(value,"hex"):Buffer.from(value,"base64");if(key.length!==32)throw new Error("AILEARN_SECRET_KEY 必须是 32 字节的 base64 或 64 位 hex");return key;}
export function loadMasterKey(dataDir=config.dataDir):Buffer{if(process.env.AILEARN_SECRET_KEY)return parseEnvKey(process.env.AILEARN_SECRET_KEY);fs.mkdirSync(dataDir,{recursive:true});const file=path.join(dataDir,".ailearn-secret");try{const key=Buffer.from(fs.readFileSync(file,"utf8").trim(),"base64");if(key.length!==32)throw new Error();return key;}catch{if(fs.existsSync(file))throw new Error("应用主密钥无效，请恢复备份或重新授权模型配置");const key=randomBytes(32);fs.writeFileSync(file,key.toString("base64"),{encoding:"utf8",mode:0o600,flag:"wx"});return key;}}
export function encryptSecret(plain:string,key:Buffer,aad:string):EncryptedSecret{const iv=randomBytes(12),cipher=createCipheriv("aes-256-gcm",key,iv);cipher.setAAD(Buffer.from(aad));const ciphertext=Buffer.concat([cipher.update(plain,"utf8"),cipher.final()]);return{version:1,algorithm:"aes-256-gcm",iv:iv.toString("base64"),authTag:cipher.getAuthTag().toString("base64"),ciphertext:ciphertext.toString("base64")};}
export function decryptSecret(envelope:EncryptedSecret,key:Buffer,aad:string):string{if(envelope.version!==1||envelope.algorithm!=="aes-256-gcm")throw new Error("Unsupported secret envelope");const decipher=createDecipheriv("aes-256-gcm",key,Buffer.from(envelope.iv,"base64"));decipher.setAAD(Buffer.from(aad));decipher.setAuthTag(Buffer.from(envelope.authTag,"base64"));return Buffer.concat([decipher.update(Buffer.from(envelope.ciphertext,"base64")),decipher.final()]).toString("utf8");}
export const legacySecretAad=(id:number,baseUrl:string)=>`ailearn:provider:${id}:${baseUrl}`;
export const secretAad=(userId:number,id:number,baseUrl:string)=>`ailearn:user:${userId}:provider:${id}:${baseUrl}`;
